### ISSUE TITLE
Identity monad but not applicative

### ISSUE THREAD

**Issue by dmbarbour** [IreneKnapp/direct-murmur-hash#1]
Apparently, monads that are not applicatives become an error in GHC 7.10.

**Comment by IreneKnapp** [comment]
Oh - thank you for telling me!  I am pleasantly surprised someone is trying to use this library. :)  I would actually have to get permission from my current employer before I could release a fix... and it's not worth it for a library that, as far as I know, nobody uses. :/  I can accept a pull request though.  Up to you whether you want to put in that effort!

**Comment by dmbarbour** [comment]
I plan to keep using this. If you'd like, you can add me as a maintainer in the cabal file.

**Comment by IreneKnapp** [comment]
Done.  Please don't be shy about making Hackage uploads as needed, and let me know if I need to do anything permissions-wise for that.  Thanks for stepping up!

**Comment by dmbarbour** [comment]
On Fri, Feb 20, 2015 at 11:36 AM, Irene Knapp notifications@github.com
wrote:

> Done. Please don't be shy about making Hackage uploads as needed, and let
> me know if I need to do anything permissions-wise for that. Thanks for
> stepping up!
> 
> To add me as a maintainer, you'll need to go to your hackage page:

https://hackage.haskell.org/package/direct-murmur-hash

And scroll down to 'Maintainers corner'. Click on the link, then Maintainer
group, then edit and add `dmbarbour` to the list. That should do it. :)

**Comment by IreneKnapp** [comment]
Done. :)
